# Generated by Django 2.0.3 on 2018-03-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('initials', models.CharField(choices=[('mr', 'MR'), ('ms', 'MS'), ('mrs', 'MRS')], default='mr', max_length=10)),
                ('uhid', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='male', max_length=10)),
                ('dob', models.DateTimeField()),
                ('son_daughter_of', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default='None', max_length=50)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
